/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI_Control;

import Person.User;
import static UserDAO.AccountServices.changeGrade;
import com.mycompany.motordrivinglicensetest.*;
import java.util.*;
import javax.swing.*;
import UserDAO.AllUser;
import javax.swing.table.DefaultTableModel;

public class Test extends javax.swing.JFrame {
    User u;
    public Test(User u) {
        this.u = u;
        initComponents();
        this.setLocationRelativeTo(null);
        BuidTest();
        BuildList();
        View();
    }
    private static int pos = 0;
    public static ArrayList<Question> listQuestions = new ArrayList<>();
    private double score = 0;

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        this.score = score;
    }
    
    public void BuidTest() {
        int size = ListQuestions.list.size();
        Set<Integer> randomNumbers = new HashSet<>();
        int rd;
        while(randomNumbers.size()<26){
            rd = (int) Math.round(Math.random() * (size - 1));
            randomNumbers.add(rd);
        }
        for (int i : randomNumbers) {
            Question q = ListQuestions.list.get(i);
            q.setSelectedAnswer("");
            listQuestions.add(q);
        }
    }

    public void BuildList() {
        DefaultListModel model = new DefaultListModel();
        this.listQ.setModel(model);
        for (int i = 0; i < 25; i++) {
            model.addElement("Câu số " + (i + 1));
        }
    }

    public void View() {
        Question q = listQuestions.get(pos);
        qusLabel.setText("Câu "+(pos+1)+": "+q.getQuestion());
        aRButton.setText(q.getAnswerA());
        bRButton.setText(q.getAnswerB());
        cRButton.setText(q.getAnswerC());
        if (q.getAnswerD().compareTo("") == 0) {
            dRButton.setVisible(false);
        } else {
            dRButton.setText(q.getAnswerD());
        }
        OnStatus(q.getSelectedAnswer());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        qusLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        submitButton = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listQ = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        aRButton = new javax.swing.JRadioButton();
        bRButton = new javax.swing.JRadioButton();
        cRButton = new javax.swing.JRadioButton();
        dRButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trắc nghiệm bằng lái xe 2 bánh");
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        qusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(qusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        submitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        submitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitButton.setText("Nộp bài");
        submitButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption), javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption)));
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitButtonMouseClicked(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("Thoát");
        exitButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaption), javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.inactiveCaption)));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(java.awt.SystemColor.inactiveCaption);
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))));

        listQ.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listQ.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listQ.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listQValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listQ);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(java.awt.SystemColor.inactiveCaption);

        buttonGroup1.add(aRButton);
        aRButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aRButton.setText("jRadioButton1");
        aRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aRButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(bRButton);
        bRButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bRButton.setText("jRadioButton2");
        bRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(cRButton);
        cRButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cRButton.setText("jRadioButton3");
        cRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(dRButton);
        dRButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dRButton.setText("jRadioButton4");
        dRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dRButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aRButton, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addComponent(bRButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cRButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dRButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(aRButton)
                .addGap(32, 32, 32)
                .addComponent(bRButton)
                .addGap(32, 32, 32)
                .addComponent(cRButton)
                .addGap(29, 29, 29)
                .addComponent(dRButton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listQValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listQValueChanged
        pos = listQ.getSelectedIndex();
        View();

    }//GEN-LAST:event_listQValueChanged

    private void aRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aRButtonActionPerformed
        if (aRButton.isSelected()) {
            Question q = listQuestions.get(pos);
            q.setSelectedAnswer("a");
            listQuestions.set(pos, q);
        }
    }//GEN-LAST:event_aRButtonActionPerformed

    private void bRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRButtonActionPerformed
        if (bRButton.isSelected()) {
            Question q = listQuestions.get(pos);
            q.setSelectedAnswer("b");
            listQuestions.set(pos, q);
        }
    }//GEN-LAST:event_bRButtonActionPerformed

    private void cRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRButtonActionPerformed
        if (cRButton.isSelected()) {
            Question q = listQuestions.get(pos);
            q.setSelectedAnswer("c");
            listQuestions.set(pos, q);
        }
    }//GEN-LAST:event_cRButtonActionPerformed

    private void dRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dRButtonActionPerformed
        if (dRButton.isSelected()) {
            Question q = listQuestions.get(pos);
            q.setSelectedAnswer("d");
            listQuestions.set(pos, q);
        }
    }//GEN-LAST:event_dRButtonActionPerformed
//chua chinh xac
    private void submitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseClicked

        for (Question q:listQuestions){
            if(q.getKey().equals(q.getSelectedAnswer())){
                score+=0.4;
            }
        }
        score = Math.ceil(score);
        resultLabel.setText("Tổng điểm: "+score);
        if(u.getGrade()<score){
            u.setGrade(score);
        }
        changeGrade(u);
    }//GEN-LAST:event_submitButtonMouseClicked

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        
        int confirm = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thoát bài thi chứ?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
                        if (confirm == JOptionPane.YES_OPTION) {
                            this.dispose();
                            new Home(u).setVisible(true);
                        }
        //this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked


    public void OnOff(boolean a, boolean b, boolean c, boolean d) {
        this.aRButton.setSelected(a);
        this.bRButton.setSelected(b);
        this.cRButton.setSelected(c);
        this.dRButton.setSelected(d);
    }

    public void OnStatus(String n) {
        switch (n) {
            case "a":
                OnOff(true, false, false, false);
                break;
            case "b":
                OnOff(false, true, false, false);
                break;
            case "c":
                OnOff(false, false, true, false);
                break;
            case "d":
                OnOff(false, false, false, true);
                break;
            default:
                this.buttonGroup1.clearSelection();
                break;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aRButton;
    private javax.swing.JRadioButton bRButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cRButton;
    private javax.swing.JRadioButton dRButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listQ;
    private javax.swing.JLabel qusLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel submitButton;
    // End of variables declaration//GEN-END:variables
}
